name: Auto Merge Staging to Main

on:
  push:
    branches:
      - staging

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <-- THIS LINE gives push access
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge staging into main
        run: |
          git fetch origin staging
          git merge origin/staging --allow-unrelated-histories --no-ff -m "Auto merge staging into main [skip ci]"

      - name: Push changes to main
        run: git push origin main
        env:
          # Use GitHub token to authenticate push
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}